name: Pages
on:
  push:
    branches: [main]      # o tu branch
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with: { version: 8, run_install: true }

      - run: cd frontend && pnpm run build

      # NUEVA versión 3 ➜ usa upload-artifact v4 internamente
      - uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write      # para OIDC
      pages: write
    # NUEVA versión 4
    steps:
      - uses: actions/deploy-pages@v4
